// Generated by https://quicktype.io

export interface ICalendarioJugadores {
    jugadoresPartido: JugadoresPartido;
}

export interface JugadoresPartido {
    equipoLocal:     EquipoLocal;
    equipoVisitante: EquipoVisitante;
}

export interface EquipoLocal {
    id:        number;
    nombre:    string;
    jugadores: Jugadores[];
}

export interface Jugadores {
    id:       number;
    nombre:   string;
    apellido: string;
}

export interface EquipoVisitante {
    id:             number;
    nombre:         string;
    nombreCompleto: string;
    fundacion:      string;
    jugadores:      Jugadores[];
}
