// Generated by https://quicktype.io

export interface IGoleadores {
    goleadores: Goleadores[];
}

export interface Goleadores {
    id:      number;
    jugador: string;
    equipo:  string;
    goles:   string;
}
