// Generated by https://quicktype.io

export interface IPosicionJugadores {
    posiciones: IPosicion[];
}

export interface IPosicion {
    id:        number;
    nombre:    string;
    createdAt: string;
    updatedAt: string;
}
