// Generated by https://quicktype.io

export interface ITablaPosiciones {
    tabla: ITabla[];
}

export interface ITabla {
    id:             number;
    nombre:         string;
    fundacion:      string;
    pj:             number;
    pg:             string;
    pp:             string;
    pe:             string;
    gf:             string;
    gc:             string;
    pt:             string;
    nombreCompleto: string;
    idCiudad:       number;
}
