// Generated by https://quicktype.io

export interface IVallaMenosVencida {
    vallaMenosVencida: VallaMenosVencida[];
}

export interface VallaMenosVencida {
    id:              number;
    nombre:          string;
    fundacion:       string;
    goles_en_contra: string;
    golesEnContra:   string;
    nombreCompleto:  string;
    idCiudad:        number;
}
